[pytest]
norecursedirs = build dist env .tox .eggs
addopts = --pep8 --flakes --doctest-glob='*.rst'
pep8maxlinelength = 120
pep8ignore =
    docs/conf.py ALL
    subliminal/__init__.py E402
flakes-ignore =
    docs/conf.py ALL
    subliminal/__init__.py UnusedImport
doctest_optionflags = NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL
markers =
    converter: tests for language code converters registered with babelfish.
    integration: tests that make remote api calls.
    pep8: used internally by pytest-pep8.
filterwarnings =
    ignore:.*imp module.*:DeprecationWarning
    ignore::DeprecationWarning:pytest_pep8.*
    ignore::DeprecationWarning:pytest_flakes.*
